# Email Configuration voor AI Media Monitor
# 
# Configuratie via .env bestand:
# 1. Kopieer .env.example naar .env
# 2. Vul je email gegevens in het .env bestand
# 3. Dit bestand gebruikt automatisch die variabelen

smtp:
  # Gmail SMTP instellingen (meest gebruikt)
  server: "${EMAIL_SMTP_SERVER}"
  port: "${EMAIL_SMTP_PORT}"
  use_tls: "${EMAIL_USE_TLS}"
  
  # Email credentials (automatisch uit .env bestand)
  username: "${EMAIL_USERNAME}"
  password: "${EMAIL_PASSWORD}"

email:
  # Afzender informatie (automatisch uit .env bestand)
  from_name: "${EMAIL_FROM_NAME}"
  from_email: "${EMAIL_USERNAME}"
  
  # Ontvanger (automatisch uit .env bestand)
  to_email: "${EMAIL_TO_ADDRESS}"
  to_name: "${EMAIL_TO_NAME}"
  
  # Email instellingen
  subject: "AI Media Monitor - Wekelijks Rapport (Week {week_number})"
  
  # HTML template voor email body
  html_template: |
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="utf-8">
        <title>AI Media Monitor Rapport</title>
        <style>
            body {{ font-family: Arial, sans-serif; line-height: 1.6; color: #333; }}
            .header {{ background: #2c3e50; color: white; padding: 20px; text-align: center; }}
            .content {{ padding: 20px; }}
            .summary {{ background: #f8f9fa; padding: 15px; border-radius: 5px; margin: 20px 0; }}
            .topic {{ margin: 20px 0; padding: 15px; border-left: 4px solid #3498db; }}
            .expert {{ margin: 15px 0; padding: 10px; background: #e8f4f8; border-radius: 5px; }}
            .footer {{ background: #95a5a6; color: white; padding: 10px; text-align: center; font-size: 12px; }}
            a {{ color: #3498db; text-decoration: none; }}
            a:hover {{ text-decoration: underline; }}
        </style>
    </head>
    <body>
        <div class="header">
            <h1>🤖 AI Media Monitor</h1>
            <p>Wekelijks Rapport - Week {week_number} van {year}</p>
        </div>
        
        <div class="content">
            <div class="summary">
                <h2>📊 Samenvatting</h2>
                <ul>
                    <li><strong>Trending Topics:</strong> {trending_topics_count}</li>
                    <li><strong>Geïdentificeerde Experts:</strong> {experts_count}</li>
                    <li><strong>Podcast Suggesties:</strong> {suggestions_count}</li>
                </ul>
            </div>
            
            {highlights_html}
            {trending_topics_html}
            {experts_html}
            {suggestions_html}
        </div>
        
        <div class="footer">
            <p>Automatisch gegenereerd door AI Media Monitor op {generation_date}</p>
            <p>📄 Volledige rapporten beschikbaar als bijlage</p>
        </div>
    </body>
    </html>

# Bijlagen
attachments:
  include_markdown: true    # Voeg markdown rapport toe als bijlage
  include_json: false       # Voeg JSON data toe als bijlage
  
# Notificatie instellingen  
notifications:
  send_on_empty: false      # Verstuur email ook als er geen nieuwe content is
  send_summary_only: false  # Verstuur alleen samenvatting (geen bijlagen)